AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 creada desde GitHub Actions

Parameters:
  InstanceDescription:
    Description: Descripcion del servidor web
    Type: String
    Default: Servidor Web Apache

  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
    Default: Acceso HTTP al servidor

Resources:

  ServerSecurityGroupClase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: SG-HTTP-Clase-CF

  MyEc2Github:
    Type: AWS::EC2::Instance
    Properties:

      ImageId: ami-0c101f26f147fa7fd
      InstanceType: t3.micro

      SecurityGroupIds:
        - !Ref ServerSecurityGroupClase

      Tags:
        - Key: Name
          Value: EC2-Clase-CF

        - Key: Proyecto
          Value: Class-CloudFormation

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd

          cat > /var/www/html/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Examen Final Arquitectura de Computadores</title>

            <style>
              body {
                font-family: Arial, sans-serif;
                text-align: center;
                background-color: #f4f4f4;
                margin-top: 100px;
              }

              h1 {
                color: #1f4e79;
              }

              h2 {
                color: #333;
              }

              .mensaje {
                color: green;
                font-weight: bold;
                margin-top: 20px;
              }
            </style>

          </head>

          <body>

            <h1>Mariana Barbosa Torrado</h1>

            <h2>Código: 0192338</h2>

            <h2>Examen Final Arquitectura de Computadores</h2>

            <p class="mensaje">
              Hice un cambio en su EC2, modificando su UserData para personalizar esta página web.
            </p>

            <button onclick="mostrarMensaje()">
              Ver mensaje
            </button>

            <script>
              function mostrarMensaje() {
                alert("UserData actualizado correctamente por Mariana Barbosa Torrado.");
              }

              console.log("UserData actualizado correctamente");
            </script>

          </body>
          </html>
          EOF

Outputs:

  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref MyEc2Github

  PublicIP:
    Description: Dirección IP pública de la instancia
    Value: !GetAtt MyEc2Github.PublicIp